### PR TITLE
Unit tests back end

### LINKED ISSUE #46: Add unit tests
Well, it needs to be done, team. We should have written the tests first. Now, they are coming to haunt all of us.

Since we're not actively using [Trello](https://trello.com/c/sxtWmIm0/56-find-unit-testing-framework) (ahem), I'm putting this big task here as an Issue. As we previously discussed, here are a few interesting testing frameworks:

- [Jest](https://jestjs.io)
- [Storybook](https://storybook.js.org)

This task can be pushed to Spring if needed.

### PR DESCRIPTION
**Pull request by silverware13**
Add unit tests for API

### CODE REVIEW

**Review by philectron — COMMENTED** [review]
Looks like you cover most of the test cases for Plan, Student Home, and Student Create Plan. I'm not familiar with Jest, but its assertions seem very easy to read. Since each of your test cases follows the setup-call-assert pattern and they all passed, I'm going to approve it.

I'm holding off on officially approving the change to prevent auto-merge.

**Review by philectron — APPROVED** [review]
Jackson approved.

**Review by JacksGo — COMMENTED** [review]
Some of the tests don't exactly adhere to Enzyme's semantics (e.g., starting each `it` construction with a verb), but this is hardly the time to nitpick this kind of thing.

**Comment by philectron** [comment]
Congrats, you're faster than the bot!

**Pull request merged**
